FormidableLabs/rescript-urql

README.md
example/app/App.re
example/app/DogList.re
example/app/Example.re
example/app/Header.re

This PR addresses #3. Now that we have successfully namespaced the module under `ReasonUrql`, the docs are updated to reflect that change. This PR also adds the convention of using a global `open` on `ReasonUrql` in the example, which makes accessing it's `module`s a little friendly (less verbose) syntax-wise.

Update README to match `ReasonUrql` namespacing.

---

LICENSE

This PR adds an MIT license to `reason-urql` so that it can be used by the open source community! 🚀🚀🚀

Add LICENSE.md for MIT license.

---

.gitignore
README.md
bsconfig.json
example/app/App.re
example/app/DogList.re
example/app/Example.re
example/app/Header.re
example/server/index.js
example/server/schema.js
package.json
src/UrqlClient.re
src/UrqlProvider.re
yarn.lock

This PR integrates `bs-fetch` to allow users to pass properly typed `fetchOptions` to their `Client` instance. It also allows users to pass their `fetchOptions` as either an object using the `FetchObj` constructor *or* as a function using the `FetchFn` constructor. It updates the docs and examples to show this new behavior. This should address #10.

Add `bs.fetch` for properly typed `fetchOptions`.

---

README.md
bsconfig.json
example/app/DogList.re
example/app/Example.re
example/app/Header.re
package.json
src/UrqlClient.re
src/UrqlConnect.re
src/UrqlMutation.re
src/UrqlQuery.re
yarn.lock

This PR adds support for custom caching in `reason-urql`. This implementation is an initial attempt at properly binding `urql`'s support for custom caches: https://github.com/FormidableLabs/urql#custom-caches.
Custom caching is an advanced feature of `urql` that is difficult to properly type, mostly because of how flexible this feature is (almost all cache management is placed on the consumer's code). This implementation can and probably should change moving forward, but this feels like a decent initial attempt.

Add support for properly typed custom caches.

---

.gitignore
__tests__/UrqlMutation_test.re
__tests__/UrqlQuery_test.re
bsconfig.json
package.json

This PR begins to address #4, which is in itself a much larger task. Here we add some basic setup for tests using [`bs-jest`](https://github.com/glennsl/bs-jest), and add initial tests for the `Query` and `Mutation` modules. There is some utility in testing that the compiled results of invoking these modules are what we expect them to be, even if we are simply binding to the JS logic itself.
Forthcoming PRs should focus on:
- `Connect`
- `Client`
- `Provider`
and one specifically should add a simple Travis setup for CI. We'll also want to do some research on coverage reporting in Jest so that we can debug the source more easily when needed.

Add initial test config and tests for Query and Mutation modules.

---

README.md
__tests__/UrqlConnect_test.re
__tests__/utils/TestUtils.re
src/UrqlConnect.re

This PR just adds a few tests to ensure the cache operations returned by `urql` to the render prop are properly converted between records and `Js.t` objects. We do expose `cacheToJs` and `cacheFromJs` functions using `[@bs.deriving converter]`, so these tests ensure these are working as expected 🎉
I also fixed a small piece of the API – `invalidate`. The `invalidate` operation accepts a single, optional argument, `~query`. If it receives this argument, it will invalidate that particular query, otherwise it will default to using the query on `Connect`. To properly type a single, optional argument, we needed to pass a final `unit` parameter. See [here](http://2ality.com/2017/12/functions-reasonml.html#with-optional-parameters-you-need-at-least-one-positional-parameter) for more explanation.

Add tests for Connect caching operations.

---

package.json
yarn.lock

This PR upgrades our devDependency and peerDependency on `urql` to `^1.0.0` and closes issue #24. We can now begin safely targeting the v1 branch with the correct version of `urql`. Since v1 publishes of `urql` are coming in hot right now, we'll want to make sure we update our `yarn.lock` every so often to make sure we have latest. We could also probably benefit from a clean `yarn.lock` to ensure we have the latest deps more generally (esp. `bs-platfotm`).

#24 Upgrade urql devDependency and peerDependency.

---

examples/1-execute-query-mutation/src/Example.re
examples/4-exchanges/bsconfig.json
examples/4-exchanges/package.json
examples/4-exchanges/public/index.html
examples/4-exchanges/src/index.re
examples/4-exchanges/webpack.config.js
examples/package.json
examples/yarn.lock
package.json
src/ReasonUrql.re
src/UrqlClient.re
src/components/UrqlMutation.re
src/components/UrqlQuery.re
src/utils/UrqlRequest.re
yarn.lock

This PR adds support for exchanges 🎉, addressing #40. The bulk of the work went into typing all of the API surface that underpins exchanges, i.e. `operation`, `operationResult`, `operationType`, `operationContext`, `exchangeInput`, and `exchangeIO`, but that was made much easier by `urql`'s TS defs.
A note on the architecture here – you'll see that `UrqlExchanges` is a `module` defined within `UrqlClient`. There's a reason for this. Exchanges accept `exchangeInput` as their single parameter, which is an object composed of `forward` (a function for forwarding operations to the next exchange) and `client` (the client instance, in this case of type `UrqlClient.t`). Because of this pairing between the types for exchanges and the type `t` of the client, the modules have to be co-located or we …

#40 Add support for exchanges.

---

__tests__/UrqlClient_test.re
__tests__/__snapshots__/UrqlClient_test.bs.js.snap
src/UrqlClient.re
src/UrqlTypes.re
src/utils/UrqlCombinedError.re

This PR adds specific bindings for `subscriptionExchange`. This exchange is a bit more complex than the others, accepting a `SubscriptionForwarder` and doing some transformations to our subscriptions under the hood. While I don't _fully_ understand how this works, I'm mostly following the interfaces outlined [here](https://github.com/FormidableLabs/urql/blob/0dfa8954c46d0b10d298805ffdad9da5c0d231f9/src/exchanges/subscription.ts#L24-L62). @kitten would appreciate your insight here as much as possible. I'll  try to get moving on implementing an example similar to @andyrichardson's to see if these bindings are halfway decent.

Add bindings for subscription exchange.

---

src/ReasonUrql.re
src/components/UrqlMutation.re
src/components/UrqlQuery.re
src/components/UrqlSubscription.re

This PR adds bindings for the `Subscription` component. These mostly follow the conventions outlined in `Query` and `Mutation`, with a few specifics that occur only on the `Subscription` component in `urql`. A few things to note:
1. The type for `handler` (`type handler('a, 'b) = ('a, 'b) => 'a`). Basically, `handler` receives the previous subscriptions and the current subscription, and returns the same structure as previous subscriptions. So type parameters are a great way to handle this. I may consider making these named arguments as well for clarity if folks agree.
2. The pattern matching in the `make` function of `Subscription`. Basically, we have two optional props, so we pattern match on a tuple of those two props (`variables` and `handler`) to determine which props to pass to …

#35 Add bindings for Subscription.

---

__tests__/UrqlClient_test.re
src/UrqlClient.re

This PR adds a few lingering methods that are exposed on the `urql` client. While we don't expect users to use these very often, it's good to keep the API 💯% compatible w/ `urql`.

Add final methods exposed by UrqlClient.

---

README.md
__tests__/UrqlClient_test.re
__tests__/__snapshots__/UrqlClient_test.bs.js.snap
docs/api.md
examples/3-mutation/src/Grid.re
src/UrqlClient.re
src/components/UrqlMutation.re
src/components/UrqlQuery.re

This PR begins to add docs in preparation for a `v1` release. These don't need to be perfectly fleshed out before we tag a `v1`, but should at least document the core API. Ideally we'll have a Getting Started guide as well just to walk someone through the very basics of creating a client, wrapping their app in a `Provider`, and creating a `Query` component. Moving forward we can create more specific guides for things like `Mutation`s and `Subscription`s.

Initial work on docs for v1.

---

bsconfig.json
examples/2-query/yarn.lock
examples/3-mutation/bsconfig.json
examples/3-mutation/package.json
examples/3-mutation/src/Dog.re
examples/3-mutation/src/DogStyles.re
examples/3-mutation/src/EmojiButton.re
examples/3-mutation/src/EmojiButtonStyles.re
examples/3-mutation/src/Grid.re
examples/3-mutation/src/GridStyles.re
examples/3-mutation/webpack.config.js
package.json
src/ReasonUrql.re
src/UrqlProvider.re
src/components/UrqlMutation.re
src/hooks/UrqlUseMutation.re
yarn.lock

This PR begins the migration process to latest ReasonReact and the JSX 3 syntax. The majority of files in this diff are some stylistic and architectural changes to the example project for `Mutation`, which now shows uses of both the `Mutation` component and the `useMutation` hook.
**API Proposal**
The idea for the API is that `useMutation` will live alongside `useQuery` and `useSubscription` in a top-level `Hooks` module. It returns a two dimensional tuple, composed of the result of executing the mutation and the `executeMutation` function, which we get for free because of the way BuckleScript handles JS arrays of fixed length: https://bucklescript.github.io/docs/en/common-data-types#tuple.
```reason
open ReasonUrql;
let query = {|
mutation likeDog($key: ID!) {
likeDog(key: $key) {
likes …
```

Migrate Provider and Mutation components to latest ReasonReact.

---

src/ReasonUrql.re
src/UrqlContext.re
src/UrqlProvider.re

Hello again! :)
I noticed only the Provider binding from urql was exposed here, whereas in the urql lib it exports Provider, Consumer and Context, so I created binding for those.
Is the intention to have 100% bindings from urql before 1.0?

Expose all of urql context

---

examples/2-query/package.json
examples/2-query/src/Monster.re
src/hooks/UrqlUseQuery.re
src/hooks/UrqlUseQuery.rei

Implementation of https://github.com/FormidableLabs/reason-urql/issues/67 for useQuery.
It seems to work out pretty cleanly for useQuery, my followup PR to useMutation is slightly worse.
Example 2-query builds and seems to work fine after the change.
(It seems like I have a different version of refmt from the normal maintainers of the project, so I did my best to keep the reformatting changes to unrelated code out of the diff to keep it small/readable)
Thoughts?
(Edit: I was thinking, it's probably worth taking a look at the component bindings to see if they could benefit from a similar change, as the use of the graphql parse function here probably introduces some difference in parsing behaviour if it's not being used on the components. I haven't done it yet because I'm mostly interested …

Typed useQuery MVP

---

examples/3-mutation/package.json
examples/3-mutation/src/Dog.re
src/hooks/UrqlUseMutation.re

The useMutation-counterpart of https://github.com/FormidableLabs/reason-urql/pull/68.
I wanted to see if the easy change for useQuery could work for useMutation as well. For the most part, it was straightforward, but I had to make a second little change to the api because the Module.make() function (the one generated by graphql_ppx that returns the {"query", "variables", "parse"} object) requires the variables to be passed in when you call it rather than as a payload to the executeMutation call.
The downside of this is that it changes the useMutation interface between the component and the hook and it's not the same interface as the js urql. One workaround we could do is passing the makeWithVariables function itself to useMutation so that usage would look like this:
```reason
let (_, …
```

Typed useMutation

---

examples/2-query/src/Monster.re
examples/2-query/src/index.re
examples/2-query/yarn.lock
examples/3-mutation/package.json
examples/3-mutation/src/Dog.re
examples/3-mutation/yarn.lock
src/components/UrqlMutation.re
src/components/UrqlQuery.re
src/hooks/UrqlUseMutation.re
src/hooks/UrqlUseMutation.rei
src/hooks/UrqlUseQuery.re
src/hooks/UrqlUseQuery.rei

This PR begins to address #70. Taking cue from the recent hooks PRs, the major change here is to introduce a type argument, `'response`, that matches the return value of calling `parse` on the data returned by `executeQuery` and `executeMutation`. `Query` and `Mutation` now also take a `request` prop in lieu of `query` and `variables`. `Subscription` will be done in a follow up since the hooks API w/ GADTs in still in flight in #73. 
Some noise in this diff is caused by `refmt` stuff, so I'll get a pre-commit hook setup w/ latest `refmt` to ensure we keep this consistent for everyone 👍
cc/ @gugahoa @Schmavery including you here as well for review if you have the time (no worries if not).

Improve type inference on components.

---

examples/2-query/src/Monster.re
examples/5-subscription/graphql_schema.json
examples/5-subscription/src/app/App.re
examples/5-subscription/src/app/Squares.re
examples/5-subscription/src/server/schema.js
src/ReasonUrql.re
src/UrqlTypes.re
src/components/UrqlSubscription.re

This PR would close #70 and #72 and, in my opinion, should be the feature cap for `v1` 🎉 After @gugahoa's awesome GADT approach for `useSubscription`, I was really excited to port it over to the `Subscription` component. However, as t[his issue demonstrates](https://github.com/reasonml/reason-react/issues/452) (thanks for opening @gugahoa) the `@react.component` PPX has no idea what to do w/ locally abstract types. Bummer.
I don't expect to see a fix for that in the near future, so, in the interest of getting `v1` out, I decided to expand the API surface to include `Subscription` and `SubscriptionWithHandler`. The former will infer `Data(d)` as the parsed result of the subscription, while the latter will infer it as the accumulator `'acc` type inferred through use of the `handler` prop. I …

Add proper type inference by way of Subscription and SubscriptionWithHandler.

---

src/components/UrqlMutation.re
src/components/UrqlQuery.re
src/components/UrqlSubscription.re
src/hooks/UrqlUseMutation.re
src/hooks/UrqlUseQuery.re
src/hooks/UrqlUseSubscription.re

Since we got closer to 1.0, I have been using reason-urql at my startup, and noticed some unexpected behaviors from the hooks.
The response from JS urql can contain data that is either `null` or `undefined`, this is not properly covered by `[@bs.optional]`, the fix is to use `Js.Nullable.t('a)`, which can be safely converted to an `option('a)`
The return value from reason-urql hooks were not safe to use in the dependency list of `useEffect`, `useMemo`, `useCallback` and similar, even though the response JS-land seems safe to use. That's caused by us converting the Js object to an Reason type, and at runtime that always creates a new object

Fix ReasonUrql hooks and components interop safety

---

src/UrqlClient.re

A signature with `~opts: option(UrqlTypes.partialOperationContext)=?` will expect `opts` of type `option(option(UrqlTypes.partialOperationContext))`, instead of the intended (I believe) `option(UrqlTypes.partialOperationContext)`

Fix executeQuery signature

---

examples/1-execute-query-mutation/package.json
examples/1-execute-query-mutation/src/App.re
examples/1-execute-query-mutation/src/ColdStart.re
examples/1-execute-query-mutation/src/Previewer.re
examples/1-execute-query-mutation/src/PreviewerStyles.re
examples/1-execute-query-mutation/yarn.lock
examples/2-query/package.json
examples/2-query/yarn.lock
examples/3-mutation/package.json
examples/3-mutation/yarn.lock
examples/4-exchanges/bsconfig.json
examples/4-exchanges/package.json
examples/4-exchanges/src/Console.re
examples/4-exchanges/src/ConsoleStyles.re
examples/4-exchanges/yarn.lock
examples/5-subscription/package.json
examples/5-subscription/src/app/bindings/SubscriptionsTransportWS.re
examples/5-subscription/yarn.lock
package.json
src/UrqlClient.re
src/UrqlTypes.re
yarn.lock

This PR attempts to do a final(ish) type pass on `UrqlTypes` and `UrqlClient`. I think we may still need to alter the APIs for `.executeQuery`, `.executeMutation`, and `.executeSubscription` on the `client` to properly infer the type of the response. We'll probably want to do something similar to what we did for the components and hooks by passing the whole request built by `graphql_ppx`, but that's a separate follow up PR. I'm considering releasing a `v1.0.0-beta.1` after these changes get in so we can give folks the hooks publicly while I get the type inference going on these methods 😄
cc/ @gugahoa @Schmavery

Type cleanup in UrqlTypes and UrqlClient.

---

__tests__/__snapshots__/UrqlClient_test.bs.js.snap
src/UrqlClient.re

When sending a `FetchFn` as `fetchOptions`, it was being called during the `Client` instantiation, but the expected behavior would be for it to be called on demand, as it is on upstream `urql` lib
This fix makes it possible to properly send a function as a `fetchOptions`, but introduce type unsafety with `Obj.magic` being called at `unwrapFetchOptions` where the type checker will just trust the user type annotation when calling it with a `None` value
To properly address that issue I believe the most sensible would be to not expose `unwrapFetchOptions` to any user. Any thoughts?
I'm marking this as WIP until that issue above is properly discussed

Properly send fetchOption fn to urql Client

---

examples/2-query/src/Monster.re
src/ReasonUrql.re
src/UrqlTypes.re
src/components/UrqlMutation.re
src/components/UrqlQuery.re
src/components/UrqlSubscription.re
src/hooks/UrqlUseMutation.re
src/hooks/UrqlUseQuery.re
src/hooks/UrqlUseSubscription.re
src/utils/UrqlCombinedError.re

This PR adds nicer bindings for `urql`'s `CombinedError` API. The previous binding were just wrong, so you couldn't actually access anything on the `Error(e)` variant. Now, `e` will come back with fields for `networkError`, `graphqlErrors`, and `response`. These fields are accessible using `##`, i.e.:
```reason
switch (e##networkError) {
| Some(exn) => /* do something with exn of type Js.Exn.t */
| None => /* no network error occurred */
}
```
I added an example of the above to `Monster.re` in `examples/2-query`.
Since `CombinedError` is a JS class instance on the `urql` side, I opted to use OCaml classes to bind it as described here: https://bucklescript.github.io/docs/en/class#bind-to-js-classes
@gugahoa let me know if this sounds like a decent enough API to you! I also thought about …

Improve combinedError API. Bind using OCaml classes.

---

examples/1-execute-query-mutation/src/Previewer.re
src/ReasonUrql.re
src/UrqlClient.re
src/UrqlTypes.re
src/hooks/UrqlUseMutation.re
src/hooks/UrqlUseQuery.re
src/utils/UrqlConverters.re

Fix #90. 
As @Schmavery pointed out in that issue, the `client`'s `execute*` methods weren't correctly inferring the types of the response data. Part of the reason was that we were just directly using `Request.createRequest`, which didn't forward along the `parse` function from the `graphql_ppx` query module (the secret sauce that allows us to infer types properly).
This PR fixes this by changing up the API a bit. `Client.execute*` methods now accept the full `graphql_ppx` query module (or a `Js.t` that fulfills the same contract if not using `graphql_ppx`), which allows us to use that `parse` function to properly infer types. In a lot of ways this mimics what we do in our hooks and components 😄
cc/ @gugahoa including you as well – let me know what you think of this. @Schmavery if you …

Add proper type inference to execute* methods on client.

---

__tests__/__snapshots__/UrqlClient_test.bs.js.snap
package.json
yarn.lock

Urql 1.3.0 has a breaking change in the useMutation hook.
(Will fill this in with more information later but basically right now the useMutation doesn't do anything, will probably repro on the example project).
Discovered during reason-dojo :)
Edit: I think that the issue miiight be that https://github.com/FormidableLabs/urql/pull/351 added a second arg to the executeMutation cb, and then bsc curries the application of the first arg (cause the bindings only think the cb takes one arg) and results in the executeMutation cb never actually getting called/executing.
Co-authored-by: @AryehAlexander
Co-authored-by: @figitaki

Pin urql version to 1.0.5

---

src/components/UrqlMutation.re
src/components/UrqlQuery.re
src/components/UrqlSubscription.re
src/hooks/UrqlUseMutation.re
src/hooks/UrqlUseQuery.re
src/hooks/UrqlUseSubscription.re

During the conversion from JS response to record, the `Data` branch is checked before the `Error` branch, but it's to my understanding that there can't be `Data` when the server returns a graphql error (Instead of an error in the schema)

Move Error branch upward

---

bsconfig.json
examples/1-execute-query-mutation/yarn.lock
examples/2-query/yarn.lock
examples/3-mutation/yarn.lock
examples/4-exchanges/yarn.lock
examples/5-subscription/src/app/bindings/SubscriptionsTransportWS.re
examples/5-subscription/yarn.lock
package.json
yarn.lock

This PR attempts to make `bs-fetch` a `peerDependency` for `reason-urql`. `bs-fetch` is solely used to type a few fields on the `Client` and the `combinedError`, but otherwise isn't actually used. It needs to be there to support the compiler in these modules, but in order to prevent our dep from conflicting with a user's own version of `bs-fetch`, we don't want to actually ship our dependency on `bs-fetch`.
cc/ @gugahoa I haven't yet ported this over to the examples, but let me know if you're able to apply this patch to see if it can help fix your issues! I think it'd be a win for the lib overall if we could remove this dependency. Will follow up on the examples tomorrow, just a bit late here in London!

Make bs-fetch a peerDependency.

---

src/utils/UrqlCombinedError.re

Hacked-together PR to expose the message field from the urql combinederror object https://github.com/FormidableLabs/urql/blob/6e0e6557b487bc2c416215a9c92cce809b8bf9df/src/utils/error.ts#L64
Might still need to test this out but I wanted to get someone's opinion on the idea.
A couple times I've wanted to just quickly log the error without needing to handle all the cases/formatting etc. In the past I've made the mistake of  just `Js.String.make`ing the error, but that just gives some `[object Object]`-style output because urql defines the toString on their error object but we convert it to a record, which doesn't have the custom toString unfortunately. I looked into exposing the toString for the record version, but then realized that all the toString does is return the `message` field …

Expose message field on combinedError

---

src/utils/UrqlCombinedError.re

Right now this is always null, since we don't match https://github.com/FormidableLabs/urql/blob/f4b11379e43ef14bbc2a5bf563a6aa2cc09b4271/src/utils/error.ts#L43
Probably we should also update `graphqlErrors` in the record to match, but since that's a breaking change, I thought it might be best done as part of something in #106?

FIx capitalization in CombinedError bindings

---

docs/api.md
examples/2-query/src/index.re
examples/4-exchanges/src/index.re
src/ReasonUrql.re
src/UrqlClient.re
src/UrqlTypes.re
src/components/UrqlMutation.re
src/components/UrqlQuery.re
src/components/UrqlSubscription.re
src/hooks/UrqlUseSubscription.re
src/utils/UrqlCombinedError.re

Fix #106 
This PR updates our `CombinedError` API to pass the `combinedError` record as the module type `t` that users will interact with. This feels more ergonomic to me and I believe @Schmavery felt the same. I also added the beginnings of docs on how to use `CombinedError`. I decided it wasn't useful to add a `.rei` file for this module b/c it is full of a bunch of BuckleScript accessors generated by all the `[@bs.deriving abstract]`, and we basically want the entirety of the module public anyway.
In terms of how we want to release this, I'm a little torn. It is a small breaking change that will (I suspect) break folks' builds, but it also feels fairly minimal. I'm inclined to release it as a minor (`v1.1.0`) but could also consider a patch (`v1.0.2`) if others feel that works better. …

Update CombinedError API to expose the combinedError record as the core module type t.

---

.github/workflows/nodejs.yml

This PR would add a step to our CI process to run each example in our `examples` directory through `bsb`, the BuckleScript compiler, to ensure that the examples still compile with the latest changes from `src`. This would remove a lot of overhead from manually checking that examples still compile on every change we make.
I am a little concerned that the script I have could potentially be a bit flaky – looping through directories like this seems potentially brittle, so I'd love to hear thoughts on a better way to accomplish this if anyone has ideas! We need to enforce that the root `src` directory is compiled first, but after that the examples can be compiled in parallel / order independent. @ryan-roemer tagging you for your CI wisdom.

Run all examples through bsb in CI.

---

__tests__/UrqlClient_test.re
__tests__/__snapshots__/UrqlClient_test.bs.js.snap
docs/api.md
package.json
src/UrqlClient.re
yarn.lock

This PR adds bindings for the `ssrExchange` to `reason-urql` and upgrades our `urql` dependency to 1.1.3 🎉 This will form the basis of our 1.1.0 release.
While binding this exchange didn't prove to be too difficult, getting a working example with NextJS was non-trivial. For the time being, I decided to skip it. A few things make this really hard:
- The need for a server-side prepass step. I was actually able to successfully bind this: https://github.com/FormidableLabs/bs-react-ssr-prepass. However, the below considerations pushed this over the edge of feasibility currently.
- The need for a higher order component to run the prepass step. Implementing HoCs in Reason is a fairly well known issue and I've never really been able to do it. This is the HoC we'd need to re-implement: …

Add bindings for ssrExchange. Upgrade to urql 1.1.3.

---

README.md

After FormidableLabs#104 was merged, you have to explicitly install bs-fetch which may not be obvious to everyone until you try to compile and it fails:
```bash
File "bsconfig.json", line 1
Error: package bs-fetch not found or built 
- Did you install it?
- If you did, did you run `bsb -make-world`?
error Command failed with exit code 2.
```
So to avoid any friction in installing the library I think it's preferable to make this explicit in step 1 such that you are not met with the error when you try to compile.

docs: Add bs-fetch peer dependency to README

---

README.md
bsconfig.json

Mention new graphql ppx in docs and remove ppx from ppx_flags in bsconfig. Fixes #117. Pinging @parkerziegler.

Mention new graphql ppx instead of old one

---

package.json
src/components/UrqlQuery.re

This change makes it possible to use `reason-urql` in projects which uses `bs-platform` 6.2.1

Fix #122 and #123

---

README.md
docs/api.md
docs/getting_started.md
src/ReasonUrql.re
src/UrqlClient.re
src/UrqlTypes.re
src/components/UrqlMutation.re
src/components/UrqlQuery.re
src/components/UrqlSubscription.re
yarn.lock

Fix #121. 
This PR begins the work to improve our API documentation and clarify language around using `graphql_ppx_re`. The biggest hurdle with the new lib is the difference in how a user derives a `graphql_schema.json` file (via `graphql-cli` rather than a local Node script that ships with the lib).
We'll probably want to begin converting our examples over gradually to use the new PPX – perhaps a good issue for a first time contributor.
I also added a bit more to our `getting_started.md` to discuss `useMutation`. Recent changes to the `urql` README added a lot of good information that it may be worthwhile to piggyback off of here as well, so I'll keep working on making the docs more usable. Open to any suggestions on how to improve things.
The last change in this PR is just ensuring …

Improve API docs, including instructions on graphql_ppx_re.

---

examples/1-execute-query-mutation/bsconfig.json
examples/1-execute-query-mutation/package.json
examples/1-execute-query-mutation/yarn.lock
examples/2-query/bsconfig.json
examples/2-query/package.json
examples/2-query/src/PokemonList.re
examples/2-query/yarn.lock
examples/3-mutation/bsconfig.json
examples/3-mutation/package.json
examples/3-mutation/yarn.lock
examples/4-exchanges/bsconfig.json
examples/4-exchanges/package.json
examples/4-exchanges/yarn.lock
examples/5-subscription/bsconfig.json
examples/5-subscription/package.json
examples/5-subscription/yarn.lock
package.json
src/UrqlClient.re
src/UrqlTypes.re
src/components/UrqlSubscription.re
src/hooks/UrqlUseMutation.re
src/hooks/UrqlUseMutation.rei
src/hooks/UrqlUseQuery.re
src/hooks/UrqlUseQuery.rei
src/hooks/UrqlUseSubscription.re
src/hooks/UrqlUseSubscription.rei
yarn.lock

Fix #126 
This PR migrates our `devDependency` on `bs-platform` to 6.2.1, which ensures that the next release of `reason-urql` will be fully compatible with the latest BuckleScript compiler. @gugahoa got the major bug in #124, so the changes here are mostly just to fix warnings and add additional code comments for contributors. If this looks good to folks I'll merge and publish v1.2.1.
I also took the time to upgrade our examples to `bs-platform` 6.2.1 and switched our PPX for GraphQL over to `@baransu/graphql_ppx_re/ppx6`, which appears to work quite well.

Migrate to bs-platform 6.2.1. Fix compiler warnings. Migrate examples.

---

docs/api.md
examples/3-mutation/package.json
examples/3-mutation/src/Dog.re
examples/3-mutation/yarn.lock
src/UrqlTypes.re
src/hooks/UrqlUseMutation.re
src/hooks/UrqlUseMutation.rei

Jumping the gun and posting this WIP PR that @sgrove wrote with me today.
This is dependent on a proposed change to graphql_ppx_re (https://github.com/baransu/graphql_ppx_re/pull/48) that would add a `definition` variable containing the query, parse function and a special `composeVariables` function that lets us do cool API things.
Wanted to get some early feedback on the first one (useDynamicMutation) that we converted, but I'm also working on similar changes to useQuery/useMutation etc which could be neat. It seems to work well so far but I'm very interested if people spot any potential issues.
In case anyone is interested, though it looks a little complicated, this shouldn't make it any harder for non-graphql_ppx_re users to use the library. They would have to write something like …

Improved useDynamicMutation API

---

.all-contributorsrc
CHANGELOG.md
README.md
docs/api.md
examples/1-execute-query-mutation/package.json
examples/1-execute-query-mutation/yarn.lock
examples/2-query/package.json
examples/2-query/yarn.lock
examples/3-mutation/package.json
examples/3-mutation/src/Dog.re
examples/3-mutation/yarn.lock
examples/4-exchanges/package.json
examples/4-exchanges/yarn.lock
examples/5-subscription/package.json
examples/5-subscription/yarn.lock
src/hooks/UrqlUseMutation.re
src/hooks/UrqlUseMutation.rei

This PR simply updates our examples to use the latest version of `graphql_ppx_re` and includes a missing dependency in `useMemo` inside of `useDynamicMutation`. Additionally, it updates the docs to make usage of `useDynamicMutation` clearer. Altogether, I think this is enough to launch v1.4.0. `useDynamicMutation` is a new addition that users can take advantage of, but the other hooks have stayed intact, hence the minor release.
My goal here is to support @robinweser's use case first. I think this will unblock a lot of `reason-urql` users who are  dependent on being able to supply variables at execution time. While I agree a larger hooks refactor to consolidate these APIs may be in order, I don't want to hold up this core feature while we refine that. I'm also optimistic that we'll one …

Prepare v1.4.0 with support for useDynamicMutation.

---

examples/5-subscription/src/app/Circles.re

Subscription example needs `unit` call to handle newly add `Client.ClientTypes.partialOperationContext`

add unit to `examples/5-subscription/src/app/Circles.re`

---

.travis.yml

This PR is here purely to see if it'll help us fix the Travis build. For some peculiar reason, Travis has decided to stop building the project before attempting to run `yarn test`. This results in build errors complaining about no tests being found 🤔 Of course, our tests need to be built to be found, so if Travis fails to run `yarn build` beforehand we'll always see this error.

Attempt to fix Travis build not building tests.

---

bsconfig.json
examples/1-execute-query-mutation/bsconfig.json
examples/1-execute-query-mutation/package.json
examples/1-execute-query-mutation/src/Previewer.re
examples/1-execute-query-mutation/yarn.lock
examples/2-query/package.json
examples/2-query/yarn.lock
examples/3-mutation/package.json
examples/3-mutation/yarn.lock
examples/4-exchanges/bsconfig.json
examples/4-exchanges/package.json
examples/4-exchanges/yarn.lock
examples/5-subscription/package.json
examples/5-subscription/yarn.lock
package.json
scripts/jest-transform-esm.js
src/UrqlClient.re
yarn.lock

This PR begins adding support for `urql` v1.5, namely the promisified `query` and `mutation` methods on the Client 🎉 This is fortunately quite easy in Reason, as the TS implementations of this just call `Wonka.take` and `Wonka.toPromise` under the hood.
As part of housekeeping, I also upgraded our BuckleScript version to 7 (finally), changed our default project compilation to ES6, and added in the proper transform to support testing, similar to what we have in [`renature`](https://github.com/FormidableLabs/renature/blob/master/scripts/jest-transform-esm.js) and what @kitten showed in his commit on the `v2` branch.
Next task will be adding support for the `useClient` hook, and then I think we'll have what we need to cut a release 🎉

Add support for promisified query and mutation methods.

---

src/UrqlClient.re

@tatchi pointed this out in #161. We never actually use the bindings for `queryJs` and `mutationJs`, we just re-implement the same methods in Reason. Just cleaning this up after the fact before releasing a new minor version.

Remove unused bindings for query and mutation.

---

src/hooks/UrqlUseSubscription.re
src/hooks/UrqlUseSubscription.rei
src/utils/UrqlGuaranteedMemo.re

This is more of an issue than a PR. `useSubscription` is currently wrapping the JS hook with `useMemo` which errors with "can't call a hook from within a hook". It wasn't immediately apparent to me why `useMemo` was being used in quite this way. I would have expected the JS component to be doing proper checks on the args provided to it and `useSubscriptionArgs` looks to me like it would create a new object on every render anyway defeating `useMemo`? Anyway, I didn't dig too deep and just removed `useMemo` here. I'm sure there was a reason I'm not seeing—maybe it's worth a comment once it gets figured out.
Thanks!

Remove useMemo from useSubscription

---

CHANGELOG.md
examples/1-execute-query-mutation/src/Previewer.re
examples/2-query/yarn.lock
examples/3-mutation/src/Dog.re
examples/3-mutation/src/DogStyles.re
examples/3-mutation/src/EmojiButton.re
examples/3-mutation/src/Loading.re
examples/3-mutation/src/LoadingStyles.re
examples/3-mutation/yarn.lock
examples/4-exchanges/yarn.lock
examples/5-subscription/yarn.lock
package.json
yarn.lock

This PR brings us up to `urql` v1.7.0! Most of the code included this PR are small updates to our examples, but no major changes to the bindings. Based on [the CHANGELOG for `urql` v1.7.0](https://github.com/FormidableLabs/urql/blob/v1.7.0/CHANGELOG.md#v170), it seemed like the major change of that version was the splitting of `urql` into separate entry points.
I'm not fully sure how we want to handle that here. From my perspective, the majority use case for using `reason-urql` is in conjunction with ReasonReact, so I'm not yet sold on splitting the bindings into a separate entry point as well (though I would love other opinions and discussion on this). If we did decide to support the separate entry point, I think it'd mostly involve:
- Modifying our `[@bs.module]` bindings for certain …

Migrate to urql v1.7.0.

---

src/Client.re
src/Client.rei

As mentioned in [this comment](https://github.com/FormidableLabs/reason-urql/pull/161#discussion_r476590067), this add extra options to the `query` and `mutation` functions to match the `executeQuery` and `executeMutation` signatures.

add more options to query and mutation

---

docs/client-and-provider.md
docs/exchanges.md
docs/getting-started.md

Fix #204 
@MoOx pointed out some glaring inconsistencies in our docs and this PR fixes them!

Fix errors in docs missed in v2 release.

---

__tests__/Types_test.re
examples/1-execute-query-mutation/webpack.config.js
examples/2-query/src/index.re
examples/2-query/webpack.config.js
examples/3-mutation/webpack.config.js
examples/4-exchanges/webpack.config.js
examples/5-subscription/src/app/index.re
examples/5-subscription/webpack.config.js
src/Client.re
src/Client.rei
src/Types.re
src/Types.rei
src/Utils.re
src/Utils.rei
src/hooks/UseMutation.re
src/hooks/UseQuery.re
src/hooks/UseSubscription.re

This PR binds the final APIs from `urql` 1.10 that I have slated for addition in #171. These include:
- Add utilities for makeResult, makeErrorResult, formatDocument, and maskTypename.
- Add enableAllOperations option on the subscriptionExchange.
- Add `client.subscription` method.
There was also a change that involved removal of our final `[@bs.deriving abstract]`, `partialOperationContext`. From what I can tell in the new ReScript docs, this is pretty much going away entirely in ReScript, so I decided to plan ahead for it. The big bummer about direct record -> object compilation, however, is that it doesn't really provide a good mechanism for generating `Partial` objects like in TS. We can't define half of these keys on a record, for example – if they're potentially undefined we have to …

Bind last APIs available in urql 1.10.

---

__tests__/Types_test.re
src/Client.re
src/Client.rei
src/GraphQLError.re
src/GraphQLError.rei
src/Types.re
src/Types.rei
src/hooks/Hooks.re
src/hooks/UseMutation.re
src/hooks/UseMutation.rei
src/hooks/UseQuery.re
src/hooks/UseQuery.rei
src/hooks/UseSubscription.re
src/hooks/UseSubscription.rei

This PR attempts to fix #202
@gaku-sei I'd love your 👀 here. The main gist of the changes:
- Treat all fields on `operationResult` as `Js.Nullable.t`s except for `operation` (which is guaranteed to be defined).
- Ensure we convert `Js.Nullable` values like `data`, `error`, `extensions`, and `stale` to `option` before operating on them.
I read your comment in #202 and agree that it's a bit uncertain where we really need the `Js.Nullable` value. From my perspective, I know that `urql` generally does a good job avoiding passing `null` in its internals, so direct `option` compilation to handle `undefined` feels ok for most cases. But agree that anything being passed through from the GraphQL server should be treated with a bit more caution.

Improve handling of potential null values from the JS side.

---

src/Client.re
src/Types.re
src/Types.rei
src/hooks/UseMutation.re
src/hooks/UseQuery.re
src/hooks/UseSubscription.re

Fix #215 
This PR ensures that `partialOperationContext` always returns a truly "partial" object. Using direct object -> record compilation is problematic for this case, because `None` will compile to `undefined` and wipe out defaults if the compiled object is being used with object spread syntax.
@gaku-sei this should fix your issues, because the compiled context objects will only include keys for properties that are passed in the labeled arguments for `executeQuery` as `Some(value)`.

Revert to using bs.deriving abstract for partialOperationContext.

---

README.md
__tests__/Types_test.re
docs/client-and-provider.md
examples/1-execute-query-mutation/package.json
examples/1-execute-query-mutation/src/Previewer.re
examples/1-execute-query-mutation/yarn.lock
examples/4-exchanges/package.json
examples/4-exchanges/public/index.css
examples/4-exchanges/src/Console.re
examples/4-exchanges/yarn.lock
examples/5-subscription/src/app/Circles.re
examples/5-subscription/src/app/Squares.re
src/Client.re
src/Client.rei
src/Types.re
src/Types.rei
src/hooks/Hooks.re
src/hooks/UseMutation.re
src/hooks/UseMutation.rei
src/hooks/UseQuery.re
src/hooks/UseQuery.rei
src/hooks/UseSubscription.re
src/hooks/UseSubscription.rei
yarn.lock

This PR does a few things:
1. Updates our `Client` APIs:
- The `~request` labeled argument is renamed to `~query`, `~mutation`, or `~subscription` depending on the method in use.
- `variables` are passed as records in the last position, if required. If the query, mutation, or subscription uses no variables, `unit` is passed in the last position.
2. Updates our documentation to reflect the `urql` `peerDependency` introduced in #224 
3. Updates our `Client` documentation to match the latest API changes.
4. Updates our binding to rename `operationName` to `kind` per [this PR](https://github.com/FormidableLabs/urql/pull/1045) in `urql` upstream.
Alongside #225 we're getting _very close_ to a usable `v3`! Moving slowly here but hoping to keep plugging away at everything while I also balance …

feat: modify Client API to place variables in last positional argument.

---

__tests__/Types_test.re
src/CombinedError.re
src/CombinedError.rei
src/Types.re
src/Types.rei
src/hooks/UseSubscription.re

With ReScript / `bs-platform` > @8, the syntax for binding JS classes to OCaml classes is no longer supported. In many ways this is a good thing — the old syntax was a bit cumbersome and circuitous. However, we still had our `CombinedError` binding using that syntax, which was always more trouble than it was worth. By the time we receive `CombinedError`, it is an _instance_ not the class itself. Therefore, we can treat it (for our purposes) more or less like a JS object. We can bind this with a record in Reason ✅ 
We also don't need to do any `Js.Nullable` conversion here from what I can tell. Based on [the types of instance properties on `CombinedError`](https://github.com/FormidableLabs/urql/blob/main/packages/core/src/utils/error.ts#L41-L45) we would get `undefined` rather than `null` …

Use a record to bind CombinedError. Prepare for ReScript migration.

---

__tests__/Client_test.res
__tests__/__snapshots__/Client_test.bs.js.snap
docs/exchanges.md
package.json
src/Client.res
src/Client.resi
yarn.lock

Fix #169 
This PR adds an incredibly simple binding for `@urql/exchange-multipart-fetch`. We really don't have much work to do on our end here other than to ensure we type the `multipartFetchExchange` function as being of type `Exchanges.t`, enabling it to be used in `reason-urql` without users having to type it themselves and futz with the API boundary. This also provides a smooth pattern for us to add other simple "ecosystem exchanges" as I like to call them.
We'll add an example down the road for these more sophisticated use cases, but for now we're just trying to get started making sure we support the broader `urql` exchanges ecosystem. I added instructions as well for how to add this exchange and install the necessary additional packages.

feat(exchanges): add binding for @urql/multipart-fetch-exchange

---

__tests__/Client_test.res
docs/exchanges.md
src/Client.res
src/Client.resi

This PR adds a binding for [`@urql/exchange-request-policy`](https://github.com/FormidableLabs/urql/tree/main/exchanges/request-policy). This was a relatively low cost effort to bind, so I thought it made sense to lump it in with the `retryExchange` before 3.3.0 goes out.
Similar to the binding for `@urql/exchange-retry`, our binding here exposes a `make` function to turn optional parameters into a typed Reason record. This function is called  `makeRequestPolicyExchangeOptions` to keep the nomenclature consistent. An example of the new API in action:
```rescript
open ReasonUrql
let shouldUpgrade = (operation: Types.operation) =>
operation.context.requestPolicy !== #CacheOnly
let requestPolicyExchangeOptions = Client.Exchanges.makeRequestPolicyExchangeOptions(
~shouldUpgrade,
~ttl=2000, …
```

feat(exchanges): add binding for @urql/exchange-request-policy

---

package.json

Since this package is compatible with ReScript it makes sense to 
add the `rescript` keyword to aid in discoverability and cause the 
package to be picked up by [the package overview on rescript-lang.org](https://rescript-lang.org/packages).

Add rescript keyword to package.json

---

__tests__/Client_test.res
docs/exchanges.md
package.json
src/Client.res
src/Client.resi
yarn.lock

This PR adds bindings for two more exchanges 🎉:
1. `@urql/exchange-persisted-fetch`
2. `@urql/exchange-refocus`
The diff is a touch wonky because I did some additional reorganization, including organizing exchanges alphabetically in source, tests, and docs. Rest assured, there were no changes to any of the other recently bound exchanges, just moving them around.
With respect to the `persistedFetchExchange`, I left out a more extensive binding for [`DocumentNode`](https://github.com/graphql/graphql-js/blob/master/src/language/ast.d.ts#L212) in favor of a type parameter, because a full `DocumentNode` binding is _way_ outside the scope of this library. This way, users can annotate the node for the access pattern they have (be it `document.documentId` or something else).

feat: add bindings for @urql/exchange-persisted-fetch and @urql/exchange-refocus

---

package.json

A tiny, smol change before the dawn of a new package name! I just wanted to get one final sign-off on the name change.
The strategy for publishing will be to:
- Merge this PR
- Publish this new version of `@urql/rescript` as v4.0.0 to continue the version continuity
- `npm deprecate` the latest version of `reason-urql` (v3.4.0) with a notice on the upgrade path
Ultimately, I settled on `@urql/rescript` for the naming of this package because it consistently follows the pattern set out by other language / framework bindings we have for `urql`, i.e. `@urql/vue`, `@urql/preact`, and `@urql/svelte`. If we do publish the bindings to `@urql/core` separately one day, I think `@urql/rescript-core` would work just fine 👍

feat: rename package to @urql/rescript

---

docs/error.md

The value under `graphQLErrors` is an array instead of an `option` so the 
example no longer compiled. Simply unwrapping the `Some` would cause 
the result to always match. Adding the extra conditional compiles down to 
a very nice set of JavaScript if-statements.
```js
case /* Error */2 :
var e = response._0;
var gqle = e.graphQLErrors;
if (e.networkError !== undefined) {
// Handle networkError
} else if (gqle.length !== 0) {
// Handle GraphQL Errors
} else {
// Handle all other errors
}
```

(docs) fix switch statement for CombinedError

---

CHANGELOG.md
__tests__/Client_test.res
docs/advanced.md
docs/client-and-provider.md
docs/error.md
docs/exchanges.md
docs/getting-started.md
docs/hooks.md

Fix #246 
This PR migrates all of our examples in documentation to ReScript! We had several Reason code samples lying around for a long time, but with the recent rename and republish, it's best to have all of our examples in our target source language.

docs: migrate all code examples to ReScript
